source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
 
inhibit_all_warnings!
use_frameworks!

target 'MindValleySample' do
end

pod "PinterestSDK", :git => "https://github.com/pinterest/ios-pdk.git"

target 'MindValleySampleTests' do
end






